# Generated by Django 6.0.2 on 2026-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_order_is_paid_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoary',
            new_name='category',
        ),
    ]
